
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()
    # ... (connection setup) ...
    conn = psycopg2.connect(dbname=os.getenv('DBNAME'), 
                            user=os.getenv('USER'), 
                            password=os.getenv('PASSWORD'),
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    
    mf_struct = {}
    
    # --- TABLE SCAN 1: populate mf-struct with distinct values of grouping attribute (V) ---
    
    cur.execute("SELECT * FROM sales")
    for row in cur:
        # Create a unique key for the group based on attributes V: ['cust']
        key = tuple(row[attr] for attr in ['cust'])
        if key not in mf_struct:
            # Initialize aggregate variables: ['count_1_quant', 'sum_2_quant']
            mf_struct[key] = {'count_1_quant': 0, 'sum_2_quant': 0}
    
    
    # --- FUTURE SCANS (2 to 3) WILL GO HERE ---
    
    output = []
    for key, aggs in mf_struct.items():
        row = {attr: key[i] for i, attr in enumerate(['cust'])}
        row.update(aggs)
        output.append(row)
        
    return tabulate.tabulate(output, headers="keys", tablefmt="psql")

if "__main__" == __name__:
    print(query())
    