
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()
    # ... (connection setup) ...
    conn = psycopg2.connect(dbname=os.getenv('DBNAME'), 
                            user=os.getenv('USER'), 
                            password=os.getenv('PASSWORD'),
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    
    mf_struct = {}
    
    # --- TABLE SCAN 1: populate mf-struct with distinct values of grouping attribute (V) ---
    
    cur.execute("SELECT * FROM sales")
    for row in cur:
        # Create a unique key for the group based on attributes V: ['state', 'month']
        key = tuple(row[attr] for attr in ['state', 'month'])
        if key not in mf_struct:
            # Initialize aggregate variables: ['count(quant)']
            mf_struct[key] = {'count(quant)': 0}
    
    
    # --- TABLE SCAN 2: simple grouped processing ---
    
    grouped_results = {}

    cur.execute("SELECT * FROM sales")
    for row in cur:
        should_use_row = True
        if not (row['year'] == 2019):
            should_use_row = False
        # Use current row when it matches the parsed filter condition
        if should_use_row:
            # Build the group key using parsed grouping attributes
            group_key = tuple(row[attr] for attr in ['state', 'month'])

            # Create a new group entry the first time we see this key
            if group_key not in grouped_results:
                grouped_results[group_key] = {
                    'count_quant': 0,
                }

            grouped_results[group_key]['count_quant'] = grouped_results[group_key]['count_quant'] + 1
    
    
    # --- FUTURE MF/EMF SCANS WILL GO HERE ---
    output = []
    if True:
        for group_key in grouped_results:
            group_data = grouped_results[group_key]

            output_row = {}
            for i, attr_name in enumerate(['state', 'month']):
                output_row[attr_name] = group_key[i]

            output_row['count(quant)'] = group_data['count_quant']
            output.append(output_row)

        # Sort grouped output so generated result is stable for testing
        output.sort(key=lambda row: tuple(row[attr_name] for attr_name in ['state']))
    else:
        for key, aggs in mf_struct.items():
            row = {attr: key[i] for i, attr in enumerate(['state', 'month'])}
            row.update(aggs)
            output.append(row)
        
    return tabulate.tabulate(output, headers="keys", tablefmt="psql")
    

if "__main__" == __name__:
    print(query())
    