
import os
import re
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    def makeAggName(expr):
        return expr.replace("(", "_").replace(")", "").replace(".", "_").replace("*", "star").replace(" ", "")

    def passesHaving(row):
        havingExpr = None
        if havingExpr is None:
            return True

        evalExpr = havingExpr
        evalExpr = re.sub(r"\bAND\b", " and ", evalExpr, flags=re.IGNORECASE)
        evalExpr = re.sub(r"\bOR\b", " or ", evalExpr, flags=re.IGNORECASE)
        evalExpr = re.sub(r"(?<![<>=!])=(?!=)", "==", evalExpr)

        aggCalls = re.findall(r"[A-Za-z_]\w*\s*\(\s*(?:[A-Za-z_][\w\.]*|\*)\s*\)", evalExpr)
        for aggExpr in sorted(set(aggCalls), key=len, reverse=True):
            evalExpr = evalExpr.replace(aggExpr, makeAggName(aggExpr))

        evalVals = {}
        for key, val in row.items():
            evalVals[makeAggName(str(key))] = val
            if re.match(r"^[A-Za-z_]\w*$", str(key)):
                evalVals[str(key)] = val

        try:
            return bool(eval(evalExpr, {"__builtins__": {}}, evalVals))
        except Exception:
            return False

    load_dotenv()
    # ... (connection setup) ...
    conn = psycopg2.connect(dbname=os.getenv('DBNAME'), 
                            user=os.getenv('USER'), 
                            password=os.getenv('PASSWORD'),
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    
    mf_struct = {}
    
    # --- TABLE SCAN 1: populate mf-struct with distinct values of grouping attribute (V) ---
    
    cur.execute("SELECT * FROM sales")
    for row in cur:
        # Create a unique key for the group based on attributes V: ['cust']
        key = tuple(row[attr] for attr in ['cust'])
        if key not in mf_struct:
            # Initialize aggregate variables: ['count(ny.quant)', 'sum(nj.quant)', 'max(ct.quant)']
            mf_struct[key] = {'count_ny_quant': 0, 'sum_nj_quant': 0, 'max_ct_quant': 0}
    
    
    # --- TABLE SCAN 2: simple grouped processing ---
    grouped_results = {}
    
    # --- MF/EMF grouping variable scan ---
    
    print('Current MF mode supports exactly one grouping variable. Input has n=3.')

    output = []
    if False:
        for groupKey in grouped_results:
            groupData = grouped_results[groupKey]

            outputRow = {}
            for i, attrName in enumerate(['cust']):
                outputRow[attrName] = groupKey[i]

            outputRow['count(ny.quant)'] = groupData['count_ny_quant']
            outputRow['sum(nj.quant)'] = groupData['sum_nj_quant']
            outputRow['max(ct.quant)'] = groupData['max_ct_quant']
            if passesHaving(outputRow):
                output.append(outputRow)

        # Sort grouped output so generated result is stable for testing
        output.sort(key=lambda outRow: tuple(outRow[attrName] for attrName in ['cust']))
    else:        
        for key, aggs in mf_struct.items():
            row = {attr: key[i] for i, attr in enumerate(['cust'])}

            for aggregateName, aggregateValue in aggs.items():
                if aggregateName.endswith("__sum"):
                    averageName = aggregateName[:-5]
                    avgCountName = averageName + "__count"
                    if avgCountName in aggs and aggs[avgCountName] != 0:
                        row[averageName] = aggs[aggregateName] / aggs[avgCountName]
                    else:
                        row[averageName] = 0
                elif aggregateName.endswith("__count") and (aggregateName[:-7] + "__sum") in aggs:
                    continue
                else:
                    row[aggregateName] = aggregateValue

            if passesHaving(row):
                output.append(row)

    return tabulate.tabulate(output, headers="keys", tablefmt="psql")
    

if "__main__" == __name__:
    print(query())
    