import subprocess
import sys
import re

def getUserInput():
    # Check if a file was provided as an argument
    if len(sys.argv) > 1:
        with open(sys.argv[1], 'r') as f:
            return parseInput(f.read())
    else:
        # Prompt the user interactively if no file is provided
        return interactiveInput()

def interactiveInput():
    print("Phi Expression:")
    phiParams = {}
    phiParams['S'] = [val.strip() for val in input("# 1. S - projected columns / expressions (comma separated): \n").split(',')]
    phiParams['n'] = int(input("# 2. number of grouping variables (int): \n"))
    phiParams['V'] = [val.strip() for val in input("# 3. V - grouping attributes (comma separated): \n").split(',')]
    phiParams['F-VECT'] = [val.strip() for val in input("# 4. F-VECT - vector of aggregate functions (comma separated): \n").split(',')]
    phiParams['PRED-LIST'] = [val.strip() for val in input("# 5. PRED-LIST - list of predicates (semicolon separated): \n").split(';')]
    
    having = input('# 6. HAVING (or NONE): \n')
    phiParams['HAVING'] = None if having.upper() == 'NONE' else having
    return phiParams

def parseInput(data):
    # Parses text file for the ESQL query
    data = " ".join(data.split())
    phiParams = {}

    try:
        # 1. Extract S (Select Attributes)
        s_match = re.search(r'SELECT (.*?) FROM', data, re.IGNORECASE)
        phiParams['S'] = [val.strip() for val in s_match.group(1).split(',')] if s_match else []

        # 2. Extract V and n (Grouping Attributes and Count)
        group_match = re.search(r'GROUP BY (.*?) SUCH THAT', data, re.IGNORECASE)
        if group_match:
            group_parts = group_match.group(1).split(';')
            phiParams['V'] = [val.strip() for val in group_parts[0].split(',')]
            variables = [val.strip() for val in group_parts[1].split(',')]
            phiParams['n'] = len(variables)
        else:
            phiParams['V'], phiParams['n'] = [], 0

        # 3. Extract F-VECT (Aggregate Functions)
        phiParams['F-VECT'] = [item for item in phiParams['S'] if '(' in item]

        # 4. Extract PRED-LIST (Predicates / Sigma)
        if 'HAVING' in data.upper():
            pred_match = re.search(r'SUCH THAT (.*?) HAVING', data, re.IGNORECASE)
        else:
            pred_match = re.search(r'SUCH THAT (.*)', data, re.IGNORECASE)
        
        phiParams['PRED-LIST'] = [val.strip() for val in pred_match.group(1).split(',')] if pred_match else []

        # 5. Extract HAVING (G)
        having_match = re.search(r'HAVING (.*)', data, re.IGNORECASE)
        if having_match:
            val = having_match.group(1).strip()
            phiParams['HAVING'] = None if val.upper() == 'NONE' else val
        else:
            phiParams['HAVING'] = None

    except Exception as e:
        print(f"Error parsing input file: {e}")
        sys.exit(1)

    return phiParams

SALES_SCHEMA = {
    "cust": "varchar(20)",
    "prod": "varchar(20)",
    "day": "integer",
    "month": "integer",
    "year": "integer",
    "state": "char(2)",
    "quant": "integer",
    "date": "date"
}

def main():
    phiParams = getUserInput()

    # Prepare aggregate initialization values
    agg_init_dict = {agg: 0 for agg in phiParams['F-VECT']}
    
    # Renamed variable to table_scan_1_code to match the document 
    table_scan_1_code = f"""
    cur.execute("SELECT * FROM sales")
    for row in cur:
        # Create a unique key for the group based on attributes V: {phiParams['V']}
        key = tuple(row[attr] for attr in {phiParams['V']})
        if key not in mf_struct:
            # Initialize aggregate variables: {phiParams['F-VECT']}
            mf_struct[key] = {agg_init_dict}
    """

    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()
    # ... (connection setup) ...
    conn = psycopg2.connect(dbname=os.getenv('DBNAME'), 
                            user=os.getenv('USER'), 
                            password=os.getenv('PASSWORD'),
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    
    mf_struct = {{}}
    
    # --- TABLE SCAN 1: populate mf-struct with distinct values of grouping attribute (V) ---
    {table_scan_1_code}
    
    # --- FUTURE SCANS (2 to {phiParams['n'] + 1}) WILL GO HERE ---
    
    output = []
    for key, aggs in mf_struct.items():
        row = {{attr: key[i] for i, attr in enumerate({phiParams['V']})}}
        row.update(aggs)
        output.append(row)
        
    return tabulate.tabulate(output, headers="keys", tablefmt="psql")

if "__main__" == __name__:
    print(query())
    """

    open("_generated.py", "w").write(tmp)
    subprocess.run(["python", "_generated.py"])

if "__main__" == __name__:
    main()